// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoGrupoG03.Models;

#nullable disable

namespace ProyectoGrupoG03.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20230619231935_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoGrupalG03.Models.Repartidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("dirección")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("horarioTrabajo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("nombreRepartidor")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("roleId");

                    b.ToTable("Repartidor");
                });

            modelBuilder.Entity("ProyectoGrupalG03.Models.Reseña", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("calificacionId")
                        .HasColumnType("int");

                    b.Property<string>("reseña")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("calificacionId");

                    b.ToTable("Reseña");
                });

            modelBuilder.Entity("ProyectoGrupalG03.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("nombreRol")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("ProyectoGrupalG03.Models.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("dirección")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("horarioApertura")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("nombreSucursal")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Sucursal");
                });

            modelBuilder.Entity("ProyectoGrupalG03.Models.calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("estrellas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("calificacion");
                });

            modelBuilder.Entity("ProyectoGrupalG03.Models.cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("dirección")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombreCliente")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("roleId");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("ProyectoGrupalG03.Models.factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("clienteId")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<int>("metodoPagoId")
                        .HasColumnType("int");

                    b.Property<int>("productoId")
                        .HasColumnType("int");

                    b.Property<string>("total")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("clienteId");

                    b.HasIndex("metodoPagoId");

                    b.HasIndex("productoId");

                    b.ToTable("factura");
                });

            modelBuilder.Entity("ProyectoGrupalG03.Models.metodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("metodo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("metodoPago");
                });

            modelBuilder.Entity("ProyectoGrupalG03.Models.pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("clienteId")
                        .HasColumnType("int");

                    b.Property<string>("especificaciones")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<int>("metodoPagoId")
                        .HasColumnType("int");

                    b.Property<int>("productoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("clienteId");

                    b.HasIndex("metodoPagoId");

                    b.HasIndex("productoId");

                    b.ToTable("pedido");
                });

            modelBuilder.Entity("ProyectoGrupalG03.Models.producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Disponibilidad")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<string>("descripción")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombreProducto")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("precio")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("producto");
                });

            modelBuilder.Entity("ProyectoGrupalG03.Models.Repartidor", b =>
                {
                    b.HasOne("ProyectoGrupalG03.Models.Role", "role")
                        .WithMany()
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("ProyectoGrupalG03.Models.Reseña", b =>
                {
                    b.HasOne("ProyectoGrupalG03.Models.calificacion", "calificacion")
                        .WithMany()
                        .HasForeignKey("calificacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("calificacion");
                });

            modelBuilder.Entity("ProyectoGrupalG03.Models.cliente", b =>
                {
                    b.HasOne("ProyectoGrupalG03.Models.Role", "role")
                        .WithMany()
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("ProyectoGrupalG03.Models.factura", b =>
                {
                    b.HasOne("ProyectoGrupalG03.Models.cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoGrupalG03.Models.metodoPago", "metodoPago")
                        .WithMany()
                        .HasForeignKey("metodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoGrupalG03.Models.producto", "producto")
                        .WithMany()
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cliente");

                    b.Navigation("metodoPago");

                    b.Navigation("producto");
                });

            modelBuilder.Entity("ProyectoGrupalG03.Models.pedido", b =>
                {
                    b.HasOne("ProyectoGrupalG03.Models.cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoGrupalG03.Models.metodoPago", "metodoPago")
                        .WithMany()
                        .HasForeignKey("metodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoGrupalG03.Models.producto", "produto")
                        .WithMany()
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cliente");

                    b.Navigation("metodoPago");

                    b.Navigation("produto");
                });
#pragma warning restore 612, 618
        }
    }
}
